# Generated by Django 4.0 on 2022-05-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
