# Generated by Django 4.0 on 2022-05-15 21:56

import customlogin.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customlogin', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', customlogin.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
